#!/usr/bin/env python3
"""Generate, compile, and benchmark a HIP GEMM kernel for canonical layouts.

A canonical word describes the physical address bits inside a matrix tile, from
least significant to most significant.  For example, ``jjjiii`` makes an 8x8
tile whose column bits are the three least-significant address bits.  Bits not
present in the word select tiles; the outer tile grid is row-major.

The three words describe the two logical dimensions of A(i, k), B(k, j), and
C(i, j), respectively.  In every word, ``i`` means the first logical matrix
dimension and ``j`` means the second.  Thus, for B, ``i`` selects k and ``j``
selects j.

This program intentionally does not submit a Flux job.  Run it from an
allocation, for example:

    python kernels/gemm/evaluate.py iijjiii jjjiiii jjjiiii --n 1024
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from string import Template


@dataclass(frozen=True)
class CanonicalLayout:
    """A two-dimensional canonical tiled layout."""

    word: str
    first_bits: int
    second_bits: int

    @property
    def tile_rows(self) -> int:
        return 1 << self.first_bits

    @property
    def tile_columns(self) -> int:
        return 1 << self.second_bits


def canonical_layout(word: str, option: str) -> CanonicalLayout:
    normalized = word.lower()
    if not normalized:
        raise ValueError(f"{option} must not be empty")
    invalid = sorted(set(normalized) - {"i", "j"})
    if invalid:
        raise ValueError(
            f"{option} must contain only 'i' and 'j' (found {''.join(invalid)!r})"
        )
    # uint32_t coordinates and shifts are used in the generated source.
    first_bits = normalized.count("i")
    second_bits = normalized.count("j")
    if first_bits > 31 or second_bits > 31 or len(normalized) > 62:
        raise ValueError(f"{option} is too wide for the generated index code")
    return CanonicalLayout(normalized, first_bits, second_bits)


def _mask(bits: int) -> str:
    return "0ull" if bits == 0 else f"0x{(1 << bits) - 1:x}ull"


def layout_function(name: str, layout: CanonicalLayout) -> str:
    """Emit a host/device offset function for a canonical word."""

    used = {"i": 0, "j": 0}
    inner_terms: list[str] = []
    physical_bit = 0
    while physical_bit < len(layout.word):
        mode = layout.word[physical_bit]
        end = physical_bit + 1
        while end < len(layout.word) and layout.word[end] == mode:
            end += 1
        width = end - physical_bit
        logical_bit = used[mode]
        used[mode] += width
        coordinate = "first" if mode == "i" else "second"
        term = (
            f"((static_cast<uint64_t>({coordinate}) >> {logical_bit}) & "
            f"{_mask(width)})"
        )
        if physical_bit:
            term += f" << {physical_bit}"
        inner_terms.append(term)
        physical_bit = end
    inner = " |\n        ".join(inner_terms)
    return f"""// word(low -> high)={layout.word}, tile={layout.tile_rows}x{layout.tile_columns}
__host__ __device__ static __forceinline__ uint64_t {name}(
    uint32_t first, uint32_t second, uint32_t n) {{
  const uint64_t outer =
      static_cast<uint64_t>(first >> {layout.first_bits}) *
          (n >> {layout.second_bits}) +
      (second >> {layout.second_bits});
  const uint64_t inner =
      {inner};
  return (outer << {len(layout.word)}) | inner;
}}"""


DRIVER_TEMPLATE = Template(
    r'''// Generated by kernels/gemm/evaluate.py.  Do not edit.
#include <hip/hip_runtime.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <numeric>
#include <vector>

#define HIP_CHECK(command)                                                    \
  do {                                                                        \
    const hipError_t error = (command);                                       \
    if (error != hipSuccess) {                                                \
      std::fprintf(stderr, "HIP error at %s:%d: %s\n", __FILE__, __LINE__, \
                   hipGetErrorString(error));                                 \
      std::exit(EXIT_FAILURE);                                                \
    }                                                                         \
  } while (0)

$layout_functions

__global__ void gemm_kernel(double* __restrict__ c,
                            const double* __restrict__ a,
                            const double* __restrict__ b,
                            double alpha, double beta, uint32_t n) {
  const uint32_t i = blockIdx.y * blockDim.y + threadIdx.y;
  const uint32_t j = blockIdx.x * blockDim.x + threadIdx.x;
  if (i >= n || j >= n) return;

  double dot = 0.0;
  for (uint32_t k = 0; k < n; ++k) {
    dot = fma(a[a_offset(i, k, n)], b[b_offset(k, j, n)], dot);
  }
  const uint64_t c_index = c_offset(i, j, n);
  c[c_index] = fma(alpha, dot, beta * c[c_index]);
}

static void validate_layout(const char* name,
                            uint64_t (*offset)(uint32_t, uint32_t, uint32_t),
                            uint32_t n) {
  const uint64_t elements = static_cast<uint64_t>(n) * n;
  std::vector<unsigned char> seen(static_cast<size_t>(elements), 0);
  for (uint32_t i = 0; i < n; ++i) {
    for (uint32_t j = 0; j < n; ++j) {
      const uint64_t physical = offset(i, j, n);
      if (physical >= elements || seen[static_cast<size_t>(physical)]) {
        std::fprintf(stderr,
                     "Layout %s is not bijective at (%u,%u): offset=%llu\n",
                     name, i, j,
                     static_cast<unsigned long long>(physical));
        std::exit(EXIT_FAILURE);
      }
      seen[static_cast<size_t>(physical)] = 1;
    }
  }
}

static double median(std::vector<double> values) {
  std::sort(values.begin(), values.end());
  const size_t middle = values.size() / 2;
  if (values.size() & 1u) return values[middle];
  return 0.5 * (values[middle - 1] + values[middle]);
}

int main() {
  constexpr uint32_t n = $n;
  constexpr int samples = $samples;
  constexpr int iterations = $iterations;
  constexpr int warmup = $warmup;
  constexpr uint32_t block_x = $block_x;
  constexpr uint32_t block_y = $block_y;
  constexpr double alpha = 1.0;
  constexpr double beta = 0.0;

  HIP_CHECK(hipSetDevice($device));
  hipDeviceProp_t properties{};
  HIP_CHECK(hipGetDeviceProperties(&properties, $device));
  std::printf("Device: %s\n", properties.name);
  std::printf("GEMM FP64: N=%u, block=%ux%u, samples=%d, iterations=%d, "
              "warmup=%d\n", n, block_x, block_y, samples, iterations,
              warmup);
  std::printf("Layouts: A=%s B=%s C=%s (words are low -> high bits)\n",
              "$a_word", "$b_word", "$c_word");

  validate_layout("A", &a_offset, n);
  validate_layout("B", &b_offset, n);
  validate_layout("C", &c_offset, n);

  const uint64_t elements = static_cast<uint64_t>(n) * n;
  const size_t bytes = static_cast<size_t>(elements * sizeof(double));
  std::vector<double> host_a(static_cast<size_t>(elements));
  std::vector<double> host_b(static_cast<size_t>(elements));
  std::vector<double> host_c(static_cast<size_t>(elements));

  // Pack deterministic logical matrices directly into their physical layouts.
  for (uint32_t i = 0; i < n; ++i) {
    for (uint32_t j = 0; j < n; ++j) {
      host_a[static_cast<size_t>(a_offset(i, j, n))] =
          static_cast<double>(static_cast<int>((i * 17u + j * 13u) % 101u) - 50) /
          101.0;
      host_b[static_cast<size_t>(b_offset(i, j, n))] =
          static_cast<double>(static_cast<int>((i * 11u + j * 19u) % 103u) - 51) /
          103.0;
      host_c[static_cast<size_t>(c_offset(i, j, n))] = 0.0;
    }
  }

  double* device_a = nullptr;
  double* device_b = nullptr;
  double* device_c = nullptr;
  HIP_CHECK(hipMalloc(&device_a, bytes));
  HIP_CHECK(hipMalloc(&device_b, bytes));
  HIP_CHECK(hipMalloc(&device_c, bytes));
  HIP_CHECK(hipMemcpy(device_a, host_a.data(), bytes, hipMemcpyHostToDevice));
  HIP_CHECK(hipMemcpy(device_b, host_b.data(), bytes, hipMemcpyHostToDevice));
  HIP_CHECK(hipMemcpy(device_c, host_c.data(), bytes, hipMemcpyHostToDevice));

  const dim3 block(block_x, block_y);
  const dim3 grid((n + block.x - 1) / block.x,
                  (n + block.y - 1) / block.y);
  auto launch = [&]() {
    hipLaunchKernelGGL(gemm_kernel, grid, block, 0, 0, device_c, device_a,
                       device_b, alpha, beta, n);
  };

  launch();
  HIP_CHECK(hipGetLastError());
  HIP_CHECK(hipDeviceSynchronize());

  // Check a few output points against a CPU reference before timing.
  HIP_CHECK(hipMemcpy(host_c.data(), device_c, bytes, hipMemcpyDeviceToHost));
  const uint32_t checks[][2] = {
      {0, 0}, {0, n - 1}, {n / 2, n / 2}, {n - 1, 0}, {n - 1, n - 1}};
  double max_abs_error = 0.0;
  double max_rel_error = 0.0;
  for (const auto& point : checks) {
    const uint32_t i = point[0];
    const uint32_t j = point[1];
    double expected = 0.0;
    for (uint32_t k = 0; k < n; ++k) {
      expected = std::fma(host_a[static_cast<size_t>(a_offset(i, k, n))],
                          host_b[static_cast<size_t>(b_offset(k, j, n))],
                          expected);
    }
    const double observed = host_c[static_cast<size_t>(c_offset(i, j, n))];
    const double absolute = std::abs(observed - expected);
    const double relative = absolute / std::max(1.0, std::abs(expected));
    max_abs_error = std::max(max_abs_error, absolute);
    max_rel_error = std::max(max_rel_error, relative);
  }
  const bool correct = max_abs_error <= 1.0e-10 || max_rel_error <= 1.0e-10;
  std::printf("Correctness: %s (5 points, max abs %.3e, max rel %.3e)\n",
              correct ? "PASS" : "FAIL", max_abs_error, max_rel_error);
  if (!correct) return EXIT_FAILURE;

  for (int iteration = 0; iteration < warmup; ++iteration) launch();
  HIP_CHECK(hipGetLastError());
  HIP_CHECK(hipDeviceSynchronize());

  hipEvent_t start{}, stop{};
  HIP_CHECK(hipEventCreate(&start));
  HIP_CHECK(hipEventCreate(&stop));
  std::vector<double> times_ms;
  times_ms.reserve(samples);
  for (int sample = 0; sample < samples; ++sample) {
    HIP_CHECK(hipEventRecord(start, 0));
    for (int iteration = 0; iteration < iterations; ++iteration) launch();
    HIP_CHECK(hipEventRecord(stop, 0));
    HIP_CHECK(hipEventSynchronize(stop));
    HIP_CHECK(hipGetLastError());
    float elapsed_ms = 0.0f;
    HIP_CHECK(hipEventElapsedTime(&elapsed_ms, start, stop));
    times_ms.push_back(elapsed_ms / iterations);
  }

  const double mean_ms =
      std::accumulate(times_ms.begin(), times_ms.end(), 0.0) / times_ms.size();
  double variance = 0.0;
  for (double time : times_ms) variance += (time - mean_ms) * (time - mean_ms);
  variance /= times_ms.size();
  const double median_ms = median(times_ms);
  const double min_ms = *std::min_element(times_ms.begin(), times_ms.end());
  const double flops = 2.0 * static_cast<double>(n) * n * n;

  std::puts("\nResults (kernel time only; packing and validation are excluded):");
  std::puts("median_ms  mean_ms  min_ms  sd_ms  GFLOP/s");
  std::printf("%9.4f  %7.4f  %6.4f  %5.4f  %8.2f\n",
              median_ms, mean_ms, min_ms, std::sqrt(variance),
              flops / (median_ms * 1.0e6));
  std::printf("Samples (ms):");
  for (double time : times_ms) std::printf(" %.4f", time);
  std::putchar('\n');

  HIP_CHECK(hipEventDestroy(start));
  HIP_CHECK(hipEventDestroy(stop));
  HIP_CHECK(hipFree(device_a));
  HIP_CHECK(hipFree(device_b));
  HIP_CHECK(hipFree(device_c));
  return EXIT_SUCCESS;
}
'''
)


def generate_source(
    layouts: tuple[CanonicalLayout, CanonicalLayout, CanonicalLayout],
    *,
    n: int,
    samples: int,
    iterations: int,
    warmup: int,
    device: int,
    block_x: int,
    block_y: int,
) -> str:
    functions = "\n\n".join(
        layout_function(name, layout)
        for name, layout in zip(("a_offset", "b_offset", "c_offset"), layouts)
    )
    return DRIVER_TEMPLATE.substitute(
        layout_functions=functions,
        n=n,
        samples=samples,
        iterations=iterations,
        warmup=warmup,
        device=device,
        block_x=block_x,
        block_y=block_y,
        a_word=layouts[0].word,
        b_word=layouts[1].word,
        c_word=layouts[2].word,
    )


def positive_integer(value: str) -> int:
    try:
        parsed = int(value)
    except ValueError as error:
        raise argparse.ArgumentTypeError(f"expected an integer, got {value!r}") from error
    if parsed <= 0:
        raise argparse.ArgumentTypeError("value must be positive")
    return parsed


def nonnegative_integer(value: str) -> int:
    try:
        parsed = int(value)
    except ValueError as error:
        raise argparse.ArgumentTypeError(f"expected an integer, got {value!r}") from error
    if parsed < 0:
        raise argparse.ArgumentTypeError("value must be nonnegative")
    return parsed


def parse_arguments(
    argv: list[str] | None = None,
) -> tuple[argparse.ArgumentParser, argparse.Namespace]:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("a_word", help="canonical word for A(i,k)")
    parser.add_argument("b_word", help="canonical word for B(k,j)")
    parser.add_argument("c_word", help="canonical word for C(i,j)")
    parser.add_argument("--n", type=positive_integer, default=256,
                        help="square matrix dimension (default: 256, matching problem.py)")
    parser.add_argument("--samples", type=positive_integer, default=10,
                        help="independent timing samples (default: 10)")
    parser.add_argument("--iterations", type=positive_integer, default=5,
                        help="kernel launches per sample (default: 5)")
    parser.add_argument("--warmup", type=nonnegative_integer, default=3,
                        help="untimed warmup launches (default: 3)")
    parser.add_argument("--device", type=nonnegative_integer, default=0,
                        help="HIP device ordinal (default: 0)")
    parser.add_argument("--block-x", type=positive_integer, default=32,
                        help="workgroup width / j threads (default: 32)")
    parser.add_argument("--block-y", type=positive_integer, default=32,
                        help="workgroup height / i threads (default: 32)")
    parser.add_argument("--compiler", default="hipcc",
                        help="HIP compiler command (default: hipcc)")
    parser.add_argument("--arch", default=None,
                        help="optional GPU architecture, for example gfx942")
    parser.add_argument("--build-dir", type=Path, default=None,
                        help="keep generated source and executable in this directory")
    parser.add_argument("--emit-only", action="store_true",
                        help="generate source but do not compile or execute it")
    return parser, parser.parse_args(argv)


def validate_configuration(
    parser: argparse.ArgumentParser,
    args: argparse.Namespace,
    layouts: tuple[CanonicalLayout, CanonicalLayout, CanonicalLayout],
) -> None:
    if args.n > 0xFFFFFFFF:
        parser.error("--n must fit in uint32_t")
    if args.samples > 0x7FFFFFFF or args.iterations > 0x7FFFFFFF:
        parser.error("--samples and --iterations must fit in a signed 32-bit integer")
    if args.warmup > 0x7FFFFFFF or args.device > 0x7FFFFFFF:
        parser.error("--warmup and --device must fit in a signed 32-bit integer")
    if args.block_x * args.block_y > 1024:
        parser.error("--block-x times --block-y must not exceed 1024")
    for label, layout in zip(("A", "B", "C"), layouts):
        if args.n % layout.tile_rows or args.n % layout.tile_columns:
            parser.error(
                f"N={args.n} must be divisible by the {layout.tile_rows}x"
                f"{layout.tile_columns} tile selected for {label} by {layout.word!r}"
            )


def run(argv: list[str] | None = None) -> int:
    parser, args = parse_arguments(argv)
    try:
        layouts = (
            canonical_layout(args.a_word, "a_word"),
            canonical_layout(args.b_word, "b_word"),
            canonical_layout(args.c_word, "c_word"),
        )
    except ValueError as error:
        parser.error(str(error))
    validate_configuration(parser, args, layouts)

    source = generate_source(
        layouts,
        n=args.n,
        samples=args.samples,
        iterations=args.iterations,
        warmup=args.warmup,
        device=args.device,
        block_x=args.block_x,
        block_y=args.block_y,
    )

    temporary: tempfile.TemporaryDirectory[str] | None = None
    if args.build_dir is None:
        if args.emit_only:
            build_dir = Path.cwd()
        else:
            temporary = tempfile.TemporaryDirectory(prefix="relay-gemm-")
            build_dir = Path(temporary.name)
    else:
        build_dir = args.build_dir.expanduser().resolve()
    build_dir.mkdir(parents=True, exist_ok=True)
    source_path = build_dir / "generated_gemm.cu"
    executable_path = build_dir / "generated_gemm"
    source_path.write_text(source)
    print(f"Generated {source_path}", flush=True)

    if args.emit_only:
        return 0

    compiler_parts = shlex.split(args.compiler)
    if not compiler_parts:
        parser.error("--compiler must not be empty")
    if shutil.which(compiler_parts[0]) is None:
        print(f"error: compiler {compiler_parts[0]!r} was not found in PATH", file=sys.stderr)
        return 2
    command = compiler_parts + ["-O3", "-std=c++17"]
    if args.arch:
        command.append(f"--offload-arch={args.arch}")
    command += [str(source_path), "-o", str(executable_path)]
    print("Compiling:", shlex.join(command), flush=True)
    try:
        subprocess.run(command, check=True)
        print(f"Running {executable_path}", flush=True)
        subprocess.run([str(executable_path)], check=True)
    except subprocess.CalledProcessError as error:
        return error.returncode or 1
    finally:
        if temporary is not None:
            temporary.cleanup()
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
