#!/usr/bin/env python3
"""Generate, compile, and benchmark HIP ATAX for a matrix layout.

A canonical word describes physical address bits inside a matrix tile from
least significant to most significant.  For example, ``jjjjiiii`` is
row-major within a 16x16 tile, while ``iiiijjjj`` is column-major within that
tile.  Bits omitted from the word select a row-major outer tile grid.

The timed operation consists of both dependent kernels, ``tmp = A*x`` and
``y = A^T*tmp``.  Vectors remain contiguous.  Run this program from a GPU
allocation, for example:

    .venv/bin/python kernels/atax/evaluate.py jjjjiiii --n 1024
"""

from __future__ import annotations

import argparse
from pathlib import Path
import shlex
import shutil
from string import Template
import subprocess
import sys
import tempfile

from relay.evaluator_dtype import EVALUATOR_DTYPES, get_evaluator_dtype
from relay.evaluator_layout import (
    CanonicalLayout,
    canonical_layout,
    layout_function,
)


DRIVER_TEMPLATE = Template(
    r'''// Generated by kernels/atax/evaluate.py.  Do not edit.
#include <hip/hip_fp16.h>
#include <hip/hip_runtime.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <numeric>
#include <vector>

#define HIP_CHECK(command)                                                    \
  do {                                                                        \
    const hipError_t error = (command);                                       \
    if (error != hipSuccess) {                                                \
      std::fprintf(stderr, "HIP error at %s:%d: %s\n", __FILE__, __LINE__, \
                   hipGetErrorString(error));                                 \
      std::exit(EXIT_FAILURE);                                                \
    }                                                                         \
  } while (0)

$layout_function

using scalar_t = $scalar_type;
using accum_t = $accumulator_type;

__host__ __device__ inline accum_t load_value(scalar_t value) {
  return $load_expression;
}

__host__ __device__ inline scalar_t store_value(accum_t value) {
  return $store_expression;
}

__global__ void atax_tmp_kernel(const scalar_t* __restrict__ a,
                                const scalar_t* __restrict__ x,
                                scalar_t* __restrict__ tmp, uint32_t n) {
  const uint32_t i = blockIdx.x * blockDim.x + threadIdx.x;
  if (i >= n) return;

  accum_t sum = 0;
  for (uint32_t j = 0; j < n; ++j) {
    sum = fma(load_value(a[a_offset(i, j, n)]), load_value(x[j]), sum);
  }
  tmp[i] = store_value(sum);
}

__global__ void atax_y_kernel(const scalar_t* __restrict__ a,
                              const scalar_t* __restrict__ tmp,
                              scalar_t* __restrict__ y, uint32_t n) {
  const uint32_t j = blockIdx.x * blockDim.x + threadIdx.x;
  if (j >= n) return;

  accum_t sum = 0;
  for (uint32_t i = 0; i < n; ++i) {
    sum = fma(load_value(a[a_offset(i, j, n)]), load_value(tmp[i]), sum);
  }
  y[j] = store_value(sum);
}

static void validate_layout(const char* name,
                            uint64_t (*offset)(uint32_t, uint32_t, uint32_t),
                            uint32_t n) {
  const uint64_t elements = static_cast<uint64_t>(n) * n;
  std::vector<unsigned char> seen(static_cast<size_t>(elements), 0);
  for (uint32_t i = 0; i < n; ++i) {
    for (uint32_t j = 0; j < n; ++j) {
      const uint64_t physical = offset(i, j, n);
      if (physical >= elements || seen[static_cast<size_t>(physical)]) {
        std::fprintf(stderr,
                     "Layout %s is not bijective at (%u,%u): offset=%llu\n",
                     name, i, j,
                     static_cast<unsigned long long>(physical));
        std::exit(EXIT_FAILURE);
      }
      seen[static_cast<size_t>(physical)] = 1;
    }
  }
}

static double median(std::vector<double> values) {
  std::sort(values.begin(), values.end());
  const size_t middle = values.size() / 2;
  if (values.size() & 1u) return values[middle];
  return 0.5 * (values[middle - 1] + values[middle]);
}

int main() {
  constexpr uint32_t n = $n;
  constexpr int samples = $samples;
  constexpr int iterations = $iterations;
  constexpr int warmup = $warmup;
  constexpr uint32_t block_size = $block_size;

  HIP_CHECK(hipSetDevice($device));
  hipDeviceProp_t properties{};
  HIP_CHECK(hipGetDeviceProperties(&properties, $device));
  std::printf("Device: %s\n", properties.name);
  std::printf("ATAX $dtype_label: N=%u, block=%u, samples=%d, iterations=%d, "
              "warmup=%d\n", n, block_size, samples, iterations, warmup);
  std::printf("Layouts: A=%s (descriptor is low -> high bits)\n", "$a_word");

  validate_layout("A", &a_offset, n);

  const uint64_t elements = static_cast<uint64_t>(n) * n;
  const size_t matrix_bytes = static_cast<size_t>(elements * sizeof(scalar_t));
  const size_t vector_bytes = static_cast<size_t>(n) * sizeof(scalar_t);
  std::vector<scalar_t> host_a(static_cast<size_t>(elements));
  std::vector<scalar_t> host_x(n);
  std::vector<scalar_t> host_tmp(n);
  std::vector<scalar_t> host_y(n);

  for (uint32_t j = 0; j < n; ++j) {
    host_x[j] = store_value(
        static_cast<accum_t>(static_cast<int>((j * 7u) % 37u) - 18) /
        static_cast<accum_t>(37));
  }
  // Pack deterministic logical A directly into its physical layout.
  for (uint32_t i = 0; i < n; ++i) {
    for (uint32_t j = 0; j < n; ++j) {
      host_a[static_cast<size_t>(a_offset(i, j, n))] = store_value(
          static_cast<accum_t>(
              static_cast<int>((i * 17u + j * 13u) % 101u) - 50) /
          static_cast<accum_t>(101));
    }
  }

  scalar_t* device_a = nullptr;
  scalar_t* device_x = nullptr;
  scalar_t* device_tmp = nullptr;
  scalar_t* device_y = nullptr;
  HIP_CHECK(hipMalloc(&device_a, matrix_bytes));
  HIP_CHECK(hipMalloc(&device_x, vector_bytes));
  HIP_CHECK(hipMalloc(&device_tmp, vector_bytes));
  HIP_CHECK(hipMalloc(&device_y, vector_bytes));
  HIP_CHECK(hipMemcpy(device_a, host_a.data(), matrix_bytes, hipMemcpyHostToDevice));
  HIP_CHECK(hipMemcpy(device_x, host_x.data(), vector_bytes, hipMemcpyHostToDevice));

  const dim3 block(block_size);
  const dim3 grid((n + block.x - 1) / block.x);
  auto launch = [&]() {
    hipLaunchKernelGGL(atax_tmp_kernel, grid, block, 0, 0, device_a, device_x,
                       device_tmp, n);
    hipLaunchKernelGGL(atax_y_kernel, grid, block, 0, 0, device_a, device_tmp,
                       device_y, n);
  };

  launch();
  HIP_CHECK(hipGetLastError());
  HIP_CHECK(hipDeviceSynchronize());
  HIP_CHECK(hipMemcpy(host_y.data(), device_y, vector_bytes, hipMemcpyDeviceToHost));

  for (uint32_t i = 0; i < n; ++i) {
    accum_t sum = 0;
    for (uint32_t j = 0; j < n; ++j) {
      sum = std::fma(
          load_value(host_a[static_cast<size_t>(a_offset(i, j, n))]),
          load_value(host_x[j]), sum);
    }
    host_tmp[i] = store_value(sum);
  }
  const uint32_t checks[] = {0, n / 4, n / 2, (3 * n) / 4, n - 1};
  double max_abs_error = 0.0;
  double max_rel_error = 0.0;
  for (uint32_t j : checks) {
    accum_t expected = 0;
    for (uint32_t i = 0; i < n; ++i) {
      expected = std::fma(
          load_value(host_a[static_cast<size_t>(a_offset(i, j, n))]),
          load_value(host_tmp[i]), expected);
    }
    const double observed = static_cast<double>(load_value(host_y[j]));
    const double reference = static_cast<double>(expected);
    const double absolute = std::abs(observed - reference);
    const double relative = absolute / std::max(1.0, std::abs(reference));
    max_abs_error = std::max(max_abs_error, absolute);
    max_rel_error = std::max(max_rel_error, relative);
  }
  const bool correct = max_abs_error <= $tolerance || max_rel_error <= $tolerance;
  std::printf("Correctness: %s (5 points, max abs %.3e, max rel %.3e)\n",
              correct ? "PASS" : "FAIL", max_abs_error, max_rel_error);
  if (!correct) return EXIT_FAILURE;

  for (int iteration = 0; iteration < warmup; ++iteration) launch();
  HIP_CHECK(hipGetLastError());
  HIP_CHECK(hipDeviceSynchronize());

  hipEvent_t start{}, stop{};
  HIP_CHECK(hipEventCreate(&start));
  HIP_CHECK(hipEventCreate(&stop));
  std::vector<double> times_ms;
  times_ms.reserve(samples);
  for (int sample = 0; sample < samples; ++sample) {
    HIP_CHECK(hipEventRecord(start, 0));
    for (int iteration = 0; iteration < iterations; ++iteration) launch();
    HIP_CHECK(hipEventRecord(stop, 0));
    HIP_CHECK(hipEventSynchronize(stop));
    HIP_CHECK(hipGetLastError());
    float elapsed_ms = 0.0f;
    HIP_CHECK(hipEventElapsedTime(&elapsed_ms, start, stop));
    times_ms.push_back(elapsed_ms / iterations);
  }

  const double mean_ms =
      std::accumulate(times_ms.begin(), times_ms.end(), 0.0) / times_ms.size();
  double variance = 0.0;
  for (double time : times_ms) variance += (time - mean_ms) * (time - mean_ms);
  variance /= times_ms.size();
  const double median_ms = median(times_ms);
  const double min_ms = *std::min_element(times_ms.begin(), times_ms.end());
  const double flops = 4.0 * static_cast<double>(n) * n;

  std::puts("\nResults (kernel time only; packing and validation are excluded):");
  std::puts("median_ms  mean_ms  min_ms  sd_ms  GFLOP/s");
  std::printf("%9.6f  %9.6f  %9.6f  %9.6f  %8.2f\n",
              median_ms, mean_ms, min_ms, std::sqrt(variance),
              flops / (median_ms * 1.0e6));
  std::printf("Samples (ms):");
  for (double time : times_ms) std::printf(" %.6f", time);
  std::putchar('\n');

  HIP_CHECK(hipEventDestroy(start));
  HIP_CHECK(hipEventDestroy(stop));
  HIP_CHECK(hipFree(device_a));
  HIP_CHECK(hipFree(device_x));
  HIP_CHECK(hipFree(device_tmp));
  HIP_CHECK(hipFree(device_y));
  return EXIT_SUCCESS;
}
'''
)


def generate_source(
    layout: CanonicalLayout,
    *,
    dtype: str = "fp64",
    n: int,
    samples: int,
    iterations: int,
    warmup: int,
    device: int,
    block_size: int,
) -> str:
    dtype_spec = get_evaluator_dtype(dtype)
    return DRIVER_TEMPLATE.substitute(
        layout_function=layout_function("a_offset", layout),
        scalar_type=dtype_spec.scalar_type,
        accumulator_type=dtype_spec.accumulator_type,
        load_expression=dtype_spec.load_expression,
        store_expression=dtype_spec.store_expression,
        dtype_label=dtype_spec.label,
        tolerance=repr(dtype_spec.tolerance),
        n=n,
        samples=samples,
        iterations=iterations,
        warmup=warmup,
        device=device,
        block_size=block_size,
        a_word=layout.word,
    )


def positive_integer(value: str) -> int:
    try:
        parsed = int(value)
    except ValueError as error:
        raise argparse.ArgumentTypeError(f"expected an integer, got {value!r}") from error
    if parsed <= 0:
        raise argparse.ArgumentTypeError("value must be positive")
    return parsed


def nonnegative_integer(value: str) -> int:
    try:
        parsed = int(value)
    except ValueError as error:
        raise argparse.ArgumentTypeError(f"expected an integer, got {value!r}") from error
    if parsed < 0:
        raise argparse.ArgumentTypeError("value must be nonnegative")
    return parsed


def parse_arguments(
    argv: list[str] | None = None,
) -> tuple[argparse.ArgumentParser, argparse.Namespace]:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("a_word", help="canonical word or linear layout for A(i,j)")
    parser.add_argument(
        "--dtype",
        choices=tuple(EVALUATOR_DTYPES),
        default="fp64",
        help="storage type; FP16 accumulates in FP32 (default: %(default)s)",
    )
    parser.add_argument(
        "--n",
        type=positive_integer,
        default=256,
        help="square matrix dimension (default: 256, matching problem.py)",
    )
    parser.add_argument(
        "--samples",
        type=positive_integer,
        default=10,
        help="independent timing samples (default: 10)",
    )
    parser.add_argument(
        "--iterations",
        type=positive_integer,
        default=5,
        help="complete two-kernel ATAX operations per sample (default: 5)",
    )
    parser.add_argument(
        "--warmup",
        type=nonnegative_integer,
        default=3,
        help="untimed complete ATAX operations (default: 3)",
    )
    parser.add_argument(
        "--device",
        type=nonnegative_integer,
        default=0,
        help="HIP device ordinal (default: 0)",
    )
    parser.add_argument(
        "--block-size",
        type=positive_integer,
        default=128,
        help="one-dimensional workgroup size for both kernels (default: 128)",
    )
    parser.add_argument(
        "--compiler",
        default="hipcc",
        help="HIP compiler command (default: hipcc)",
    )
    parser.add_argument(
        "--arch",
        default=None,
        help="optional GPU architecture, for example gfx942",
    )
    parser.add_argument(
        "--build-dir",
        type=Path,
        default=None,
        help="keep generated source and executable in this directory",
    )
    parser.add_argument(
        "--emit-only",
        action="store_true",
        help="generate source but do not compile or execute it",
    )
    return parser, parser.parse_args(argv)


def validate_configuration(
    parser: argparse.ArgumentParser,
    args: argparse.Namespace,
    layout: CanonicalLayout,
) -> None:
    if args.n > 0xFFFFFFFF:
        parser.error("--n must fit in uint32_t")
    if args.samples > 0x7FFFFFFF or args.iterations > 0x7FFFFFFF:
        parser.error("--samples and --iterations must fit in a signed 32-bit integer")
    if args.warmup > 0x7FFFFFFF or args.device > 0x7FFFFFFF:
        parser.error("--warmup and --device must fit in a signed 32-bit integer")
    if args.block_size > 1024:
        parser.error("--block-size must not exceed 1024")
    if args.n % layout.tile_rows or args.n % layout.tile_columns:
        parser.error(
            f"N={args.n} must be divisible by the {layout.tile_rows}x"
            f"{layout.tile_columns} tile selected for A by {layout.word!r}"
        )


def run(argv: list[str] | None = None) -> int:
    parser, args = parse_arguments(argv)
    try:
        layout = canonical_layout(args.a_word, "a_word")
    except ValueError as error:
        parser.error(str(error))
    validate_configuration(parser, args, layout)

    source = generate_source(
        layout,
        dtype=args.dtype,
        n=args.n,
        samples=args.samples,
        iterations=args.iterations,
        warmup=args.warmup,
        device=args.device,
        block_size=args.block_size,
    )

    temporary: tempfile.TemporaryDirectory[str] | None = None
    if args.build_dir is None:
        if args.emit_only:
            build_dir = Path.cwd()
        else:
            temporary = tempfile.TemporaryDirectory(prefix="relay-atax-")
            build_dir = Path(temporary.name)
    else:
        build_dir = args.build_dir.expanduser().resolve()
    build_dir.mkdir(parents=True, exist_ok=True)
    source_path = build_dir / "generated_atax.cu"
    executable_path = build_dir / "generated_atax"
    source_path.write_text(source)
    print(f"Generated {source_path}", flush=True)

    if args.emit_only:
        return 0

    compiler_parts = shlex.split(args.compiler)
    if not compiler_parts:
        parser.error("--compiler must not be empty")
    if shutil.which(compiler_parts[0]) is None:
        print(
            f"error: compiler {compiler_parts[0]!r} was not found in PATH",
            file=sys.stderr,
        )
        return 2
    command = compiler_parts + ["-O3", "-std=c++17"]
    if args.arch:
        command.append(f"--offload-arch={args.arch}")
    command += [str(source_path), "-o", str(executable_path)]
    print("Compiling:", shlex.join(command), flush=True)
    try:
        subprocess.run(command, check=True)
        print(f"Running {executable_path}", flush=True)
        subprocess.run([str(executable_path)], check=True)
    except subprocess.CalledProcessError as error:
        return error.returncode or 1
    finally:
        if temporary is not None:
            temporary.cleanup()
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
