"""Parse and aggregate NVIDIA Nsight Compute Stage-1 counters."""

from __future__ import annotations

import csv
from math import isfinite
from pathlib import Path
import statistics
from typing import Mapping, Sequence


FIRST_LEVEL_COUNTER = "l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum"
GLOBAL_LOAD_REQUESTS_COUNTER = "l1tex__t_requests_pipe_lsu_mem_global_op_ld.sum"
TEX_SOURCE_L2_READ_REQUESTS_COUNTER = "lts__t_requests_srcunit_tex_op_read.sum"
L1_TO_L2_READ_COUNTER = "lts__t_sectors_srcunit_tex_op_read.sum"
L2_READ_WORK_COUNTER = L1_TO_L2_READ_COUNTER
L2_READ_MISS_COUNTER = "lts__t_sectors_op_read_lookup_miss.sum"
HBM_READ_COUNTER = "dram__bytes_read.sum"
DURATION_METRIC = "gpu__time_duration.sum"
NATIVE_UNIT = "32-byte global-load L1TEX sector"
COUNTER_METRICS = (
    FIRST_LEVEL_COUNTER,
    GLOBAL_LOAD_REQUESTS_COUNTER,
    TEX_SOURCE_L2_READ_REQUESTS_COUNTER,
    L1_TO_L2_READ_COUNTER,
    L2_READ_MISS_COUNTER,
    HBM_READ_COUNTER,
    DURATION_METRIC,
)
SUMMARY_METRICS = (
    "first_level_memory_accesses",
    "tex_source_l2_read_requests",
    "l1_miss_demand_to_l2",
    "l1_to_l2_read_traffic",
    "l2_read_work",
    "l2_read_misses",
    "hbm_read_bytes",
    "global_load_requests",
    "sectors_per_request",
    "duration_ns",
)


def counter_definitions() -> dict[str, str]:
    return {
        FIRST_LEVEL_COUNTER: (
            "Nsight Compute sum of 32-byte L1TEX sectors requested by "
            "global load instructions"
        ),
        GLOBAL_LOAD_REQUESTS_COUNTER: (
            "Nsight Compute sum of L1TEX requests generated by global "
            "load instructions"
        ),
        TEX_SOURCE_L2_READ_REQUESTS_COUNTER: (
            "Nsight Compute read requests presented to L2 by TEX/L1TEX "
            "source units"
        ),
        L1_TO_L2_READ_COUNTER: (
            "Nsight Compute sum of read sectors presented to L2 by TEX "
            "source units; used for both L1-to-L2 read traffic and L2 read work"
        ),
        L2_READ_MISS_COUNTER: (
            "Nsight Compute sum of read sectors that miss the L2 lookup"
        ),
        HBM_READ_COUNTER: "Nsight Compute DRAM read volume in bytes",
        DURATION_METRIC: "Nsight Compute kernel duration in nanoseconds",
        "first_level_memory_accesses": (
            f"analysis field backed by {FIRST_LEVEL_COUNTER}; native unit is "
            f"one {NATIVE_UNIT}"
        ),
        "tex_source_l2_read_requests": (
            f"analysis field backed by {TEX_SOURCE_L2_READ_REQUESTS_COUNTER}"
        ),
        "l1_miss_demand_to_l2": (
            "primary cross-platform analysis alias for "
            "tex_source_l2_read_requests"
        ),
        "l1_to_l2_read_traffic": f"analysis field backed by {L1_TO_L2_READ_COUNTER}",
        "l2_read_work": f"analysis field backed by {L2_READ_WORK_COUNTER}",
        "l2_read_misses": f"analysis field backed by {L2_READ_MISS_COUNTER}",
        "hbm_read_bytes": f"analysis field backed by {HBM_READ_COUNTER}",
        "global_load_requests": (
            f"analysis field backed by {GLOBAL_LOAD_REQUESTS_COUNTER}"
        ),
        "sectors_per_request": (
            "derived coalescing measure: global-load L1TEX sectors divided "
            "by global-load L1TEX requests"
        ),
    }


def _number(record: Mapping[str, str], field: str, path: Path) -> float:
    value = record.get(field, "").replace(",", "").strip()
    if not value or value.lower() == "n/a":
        raise ValueError(f"{path} has an empty profiler field {field!r}")
    try:
        parsed = float(value)
    except ValueError as error:
        raise ValueError(
            f"{path} has invalid {field!r} value {value!r}"
        ) from error
    if not isfinite(parsed):
        raise ValueError(f"{path} has non-finite {field!r} value {value!r}")
    return parsed


def _records(path: Path) -> list[dict[str, str]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    header = None
    for index, line in enumerate(lines):
        fields = next(csv.reader((line,)), ())
        if "Kernel Name" in fields and all(
            metric in fields for metric in COUNTER_METRICS
        ):
            header = index
            break
    if header is None:
        raise ValueError(
            f"{path} has no Nsight Compute raw-page header for all requested "
            "metrics"
        )
    return list(csv.DictReader(lines[header:]))


def _dispatch(record: Mapping[str, str], path: Path) -> dict[str, object]:
    counters = {
        metric: _number(record, metric, path) for metric in COUNTER_METRICS
    }
    sectors = counters[FIRST_LEVEL_COUNTER]
    requests = counters[GLOBAL_LOAD_REQUESTS_COUNTER]
    l2_requests = counters[TEX_SOURCE_L2_READ_REQUESTS_COUNTER]
    if requests <= 0.0:
        raise ValueError(f"{path} has no global-load L1TEX requests")
    return {
        "index": int(record["ID"]),
        "kernel_name": record["Kernel Name"],
        "duration_ns": counters[DURATION_METRIC],
        "first_level_memory_accesses": sectors,
        "native_counter": FIRST_LEVEL_COUNTER,
        "native_unit": NATIVE_UNIT,
        "tex_source_l2_read_requests": l2_requests,
        "l1_miss_demand_to_l2": l2_requests,
        "l1_to_l2_read_traffic": counters[L1_TO_L2_READ_COUNTER],
        "l2_read_work": counters[L2_READ_WORK_COUNTER],
        "l2_read_misses": counters[L2_READ_MISS_COUNTER],
        "hbm_read_bytes": counters[HBM_READ_COUNTER],
        "global_load_requests": requests,
        "sectors_per_request": sectors / requests,
        "counters": counters,
    }


def _median(values: Sequence[float]) -> float:
    return float(statistics.median(values))


def summarize_dispatches(
    dispatches: Sequence[Mapping[str, object]],
) -> dict[str, object]:
    if not dispatches:
        raise ValueError("cannot summarize an empty dispatch population")
    summary = {
        field: _median([float(dispatch[field]) for dispatch in dispatches])
        for field in SUMMARY_METRICS
    }
    summary["native_counters"] = {
        metric: _median(
            [float(dispatch["counters"][metric]) for dispatch in dispatches]
        )
        for metric in COUNTER_METRICS
    }
    summary["native_counter"] = FIRST_LEVEL_COUNTER
    summary["native_unit"] = NATIVE_UNIT
    summary["dispatch_count"] = len(dispatches)
    return summary


def parse_counter_csv(
    path: Path,
    *,
    kernel_name: str,
    profile_iterations: int,
) -> dict[str, object]:
    """Return the final steady-state target launches from ncu raw CSV."""

    records = [
        record
        for record in _records(path)
        if kernel_name in record.get("Kernel Name", "")
    ]
    records.sort(key=lambda record: int(record["ID"]))
    if len(records) < profile_iterations:
        raise ValueError(
            f"{path} contains {len(records)} {kernel_name} launches; "
            f"expected at least {profile_iterations}"
        )
    dispatches = [
        _dispatch(record, path)
        for record in records[-profile_iterations:]
    ]
    return {
        "target_dispatch_count": len(records),
        "steady_state": summarize_dispatches(dispatches),
        "steady_dispatches": dispatches,
    }


def aggregate_profiles(
    profiles: Sequence[Mapping[str, object]],
) -> dict[str, object]:
    """Aggregate launches by their within-launch and cross-launch medians."""

    if not profiles:
        raise ValueError("counter aggregation requires at least one profile")
    launch_summaries = [profile["steady_state"] for profile in profiles]
    aggregate = {}
    for field in SUMMARY_METRICS:
        values = [float(summary[field]) for summary in launch_summaries]
        aggregate[field] = _median(values)
        aggregate[f"{field}_by_launch"] = values
    aggregate["native_counters"] = {}
    for metric in COUNTER_METRICS:
        values = [
            float(summary["native_counters"][metric])
            for summary in launch_summaries
        ]
        aggregate["native_counters"][metric] = _median(values)
        aggregate["native_counters"][f"{metric}_by_launch"] = values
    aggregate["profile_launch_count"] = len(profiles)
    aggregate["native_counter"] = FIRST_LEVEL_COUNTER
    aggregate["native_unit"] = NATIVE_UNIT
    aggregate["dispatches_per_launch"] = [
        int(summary["dispatch_count"]) for summary in launch_summaries
    ]
    return {"steady_state": aggregate, "profiles": list(profiles)}
